package com.lp.mapper;

import com.lp.pojo.Table2;
import com.lp.pojo.Table2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Table2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    long countByExample(Table2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int deleteByExample(Table2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int insert(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int insertSelective(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    List<Table2> selectByExample(Table2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    Table2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Table2 record, @Param("example") Table2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Table2 record, @Param("example") Table2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Table2 record);
}